version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Bw8mMBYaPPSDSYNg
      POSTGRES_USER: postgres.speugasgfefggbpohcod
      POSTGRES_DB: postgres
  app:
    image: dynamitesbackend
    ports:
      - 8080:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
