version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV}
      POSTGRES_USER: ${DB_USER_DEV}
      POSTGRES_DB: ${DB_NAME_DEV}
    ports:
      - '5431:5432'

  app:
    build: .
    ports:
      - '8080:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
