name: CI for ecomm-project for Dynamite

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test --if-present
      - run: npm run build --if-present
      - run: npm run test:ci --if-present
      - run: npx update-badge
      - run: npm run lint --if-present
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          allow-empty: true
    env:
      DB_PORT_DEV: ${{ secrets.DB_PORT_DEV }}
      DB_USER_DEV: ${{ secrets.DB_USER_DEV }}
      DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
      DB_NAME_DEV: ${{ secrets.DB_NAME_DEV }}
      DB_HOST_DEV: ${{ secrets.DB_HOST_DEV }}
      APP_URL: ${{ secrets.APP_URL }}
      ALL: ${{ secrets.ALL }}
      DOCS: ${{ secrets.DOCS }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
      DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
      DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD_TEST }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
      DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
      MAILGUN_TOKEN: ${{ secrets.MAILGUN_TOKEN }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
      FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
      FACEBOOK_CALLBACK_URL: ${{ secrets.FACEBOOK_CALLBACK_URL }}
      COOKIES_KEY: ${{ secrets.COOKIES_KEY }}
