name: CI for ecomm-project for Dynamite

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test --if-present
    - run: npm run build --if-present
    - run: npm run test:ci --if-present
    - run: npm run lint --if-present
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        allow-empty: true
    env:
      DB_PORT_DEV: ${{ secrets.DB_PORT_DEV }}
      DB_USER_DEV: ${{ secrets.DB_USER_DEV }}
      DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
      DB_NAME_DEV: ${{ secrets.DB_NAME_DEV }}
      DB_HOST_DEV: ${{ secrets.DB_HOST_DEV }}
      APP_URL: ${{ secrets.APP_URL }}
      ALL: ${{ secrets.ALL }}
      DOCS: ${{ secrets.DOCS }}
      APP_PORT: ${{ secrets.APP_PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
      DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
      DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD_TEST }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
      DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
      MAILERSEND_TOKEN: ${{ secrets.MAILERSEND_TOKEN }}
      MAILERSEND_DOMAIN: ${{ secrets.MAILERSEND_DOMAIN }}


